In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/A232 /Data Analytics/lab/rollingsales_bronx.xlsx')

In [13]:
df.head()

,Bronx Rolling Sales. All Sales From April 2023 - March 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,PTS Sales Data as of 04/12/2024,Unnamed: 20
0,"For sales prior to the Final Roll, Neighborhoo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Building Class Category is based on Building C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note: Condominium and cooperative sales are on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1,0,1,1646,1497,1899,1,A1,215000,2023-04-18 00:00:00

In [14]:
df.columns

Index(['Bronx Rolling Sales.  All Sales From April 2023 - March 2024',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'PTS Sales Data as of 04/12/2024', 'Unnamed: 20'],
      dtype='object')

In [15]:
cols = df.columns
new_cols = []
for column in cols:
    proper_cols = column.title()
    proper_cols_hyphen = proper_cols.replace(" ", "_")
    clean_col = proper_cols_hyphen.replace("-", "_")
    new_cols.append(clean_col)

new_cols
df.columns = new_cols

df.head()

,Bronx_Rolling_Sales.__All_Sales_From_April_2023___March_2024,Unnamed:_1,Unnamed:_2,Unnamed:_3,Unnamed:_4,Unnamed:_5,Unnamed:_6,Unnamed:_7,Unnamed:_8,Unnamed:_9,...,Unnamed:_11,Unnamed:_12,Unnamed:_13,Unnamed:_14,Unnamed:_15,Unnamed:_16,Unnamed:_17,Unnamed:_18,Pts_Sales_Data_As_Of_04/12/2024,Unnamed:_20
0,"For sales prior to the Final Roll, Neighborhoo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Building Class Category is based on Building C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note: Condominium and cooperative sales are on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,66,NaN,A1,4453 PARK AVENUE,NaN,...,1,0,1,1646,1497,1899,1,A1,215000,2023-04-18 00:00:00

In [16]:
df.tail()

,Bronx_Rolling_Sales.__All_Sales_From_April_2023___March_2024,Unnamed:_1,Unnamed:_2,Unnamed:_3,Unnamed:_4,Unnamed:_5,Unnamed:_6,Unnamed:_7,Unnamed:_8,Unnamed:_9,...,Unnamed:_11,Unnamed:_12,Unnamed:_13,Unnamed:_14,Unnamed:_15,Unnamed:_16,Unnamed:_17,Unnamed:_18,Pts_Sales_Data_As_Of_04/12/2024,Unnamed:_20
5688,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 3I",NaN,...,NaN,NaN,NaN,NaN,NaN,1957,2,D4,125000,2023-05-09 00:00:00
5689,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 5C",NaN,...,NaN,NaN,NaN,NaN,NaN,1957,2,D4,135000,2023-10-16 00:00:00
5690,2,WOODLAWN,10 COOPS - ELEVATOR APARTMENTS,2,3398,97,NaN,D4,"4295 WEBSTER AVENUE, 5F",NaN,...,NaN,NaN,NaN,NaN,NaN,1957,2,D4,265000,2023-09-07 00:00:00
5691,2,WOODLAWN,22 STORE BUILDINGS,4,3380,46,NaN,K1,4361 KATONAH AVENUE,NaN,...,0,1,1,9699,3400,1970,4,K1,0,2023-04-17 00:00:00
5692,2,WOODLAWN,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,3380,54,NaN,P8,4351 KATONAH AVENUE,NaN,...,0,1,1,3121,2520,1970,4,P8,0,2023-04-17 00:00:00

In [17]:
df.dtypes

Bronx_Rolling_Sales.__All_Sales_From_April_2023___March_2024    object
Unnamed:_1                                                      object
Unnamed:_2                                                      object
Unnamed:_3                                                      object
Unnamed:_4                                                      object
Unnamed:_5                                                      object
Unnamed:_6                                                      object
Unnamed:_7                                                      object
Unnamed:_8                                                      object
Unnamed:_9                                                      object
Unnamed:_10                                                     object
Unnamed:_11                                                     object
Unnamed:_12                                                     object
Unnamed:_13                                                     object
Unnamed:_14                                                     object
Unnamed:_15                                                     object
Unnamed:_16                                                     object
Unnamed:_17                                                     object
Unnamed:_18                                                     object
Pts_Sales_Data_As_Of_04/12/2024                                 object
Unnamed:_20                                                     object
dtype: object